apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'devops-433705-app'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pdpoornima/dvops.git'
    targetRevision: HEAD
    path: kustomize/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true