options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'  # Change here to match the cluster's node type
  
steps:
  # Step 1: Authenticate with the Kubernetes cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'my-gke-cluster'
      - '--zone'
      - 'us-east5-a'
      - '--project'
      - 'devops-433705'

  # Step 2: Apply the deployment and service YAMLs
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set compute/region us-east5
        gcloud config set compute/zone us-east5-a
        kubectl apply -k .


  # Step 3: Verify the deployments
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/frontend-node'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/npm'


timeout: 1200s
#logsBucket: "gs://mybuildbucket"