steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
availableSecrets:
  secretManager:
  - versionName: projects/devops-433705/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/devops-433705/secrets/docker-username/versions/1
    env: 'USERNAME'

  # Step 2: Pull NGINX Image from Docker Hub (Optional if you don't want to rebuild)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull NGINX Image'
    args: ['pull', 'poornima7/nginx:latest']

  # Step 3: Pull npm Image from Docker Hub (Optional if you don't want to rebuild)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull npm Image'
    args: ['pull', 'poornima7/hello-gitops:22']

  # Step 4: Deploy using kustomization.yaml to Kubernetes (GKE)
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    args: ['apply', '-k', './k8s']

  # Step 5: Check the Deployment status
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Check Deployment'
    args: ['rollout', 'status', 'deployment/nginx']

  # Your build steps here
timeout: "1200s"
logsBucket: "gs://mybuildbucket"