steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

 # Pull NGINX frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'poornima7/nginx:latest']

  # Pull npm backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'poornima7/hello-gitops:22']

availableSecrets:
  secretManager:
  - versionName: "projects/devops-433705/secrets/docker-username/versions/latest"
    env: 'USERNAME'
  - versionName: "projects/devops-433705/secrets/docker-password/versions/latest"
    env: 'PASSWORD'

 
  # Step 4: Deploy using kustomization.yaml to Kubernetes (GKE)
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    args: ['apply', '-k', './k8s']

  # Step 5: Check the Deployment status
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Check Deployment'
    args: ['rollout', 'status', 'deployment/nginx']

  # Your build steps here
timeout: "1200s"
logsBucket: "gs://mybuildbucket"