options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'  # Change here to match the cluster's node type
  
steps:
  # Step 1: Authenticate with the Kubernetes cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'my-gke-cluster'
      - '--zone'
      - 'us-east5-a'
      - '--project'
      - 'devops-433705'
  # Step 2: Create the "gitops" namespace
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'create'
      - 'namespace'
      - 'gitops'

  # Step 3: Apply the deployment and service YAMLs
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set compute/region us-east5
        gcloud config set compute/zone us-east5-a
        kubectl apply -k kustomize/base

timeout: 1200s
#logsBucket: "gs://mybuildbucket"