options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'  # Change here to match the cluster's node type
  
steps:
  # Step 0: Set up Terraform
  - name: 'hashicorp/terraform:1.0.0'
    id: 'terraform-init'
    args: ['init']
  - name: 'hashicorp/terraform:1.0.0'
    id: 'terraform-apply'
    args: ['apply', '-auto-approve']

