apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-node
  namespace: gitops
  labels:
    app: frontend-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-node
  template:
    metadata:
      labels:
        app: frontend-node
    spec:
      containers:
      - name: frontend-node
        image: gcr.io/devops-433705/nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm
  namespace: gitops
  labels:
    app: npm
spec:
  replicas: 4
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
      - name: npm
        image: gcr.io/devops-433705/hello-gitops:22
        ports:
        - containerPort: 3001