apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
#namespace: gitops
images:
- name: nginx
  newName: poornima7/nginx
  newTag: latest
- name: npm
  newName: poornima7/hello-gitops
  newTag: "22"
