apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: gitops
images:
- name: nginx
  newName: gcr.io/devops-433705/nginx:latest
  newTag: latest
- name: npm
  newName: gcr.io/devops-433705/hello-gitops:22
  newTag: "22"
