---
apiVersion: v1
kind: Service
metadata:
  #annotations:
  # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
  #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: frontend-node
  namespace: gitops
  labels:
    app: frontend-node
spec:
  ports:
    - name: "http"
      port: 8000
      targetPort: 80
  selector:
    app: frontend-node
  type: LoadBalancer  

---
apiVersion: v1
kind: Service
metadata:
  #annotations:
  # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
  #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: npm
  namespace: gitops
  labels:
    app: npm
spec:
  ports:
    - name: "http"
      port: 3001
      targetPort: 3001
  selector:
    app: npm

