name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip install --user ansible
        # Add the user's local binary path to the PATH
        echo "${{ runner.env.HOME }}/.local/bin" >> $GITHUB_PATH

    - name: Install Packer
      run: |
        # Download Packer binary
        curl -Lo packer.zip https://releases.hashicorp.com/packer/1.12.0/packer_1.12.0_linux_amd64.zip
        unzip packer.zip
        mv packer ~/.local/bin/
        echo "${{ runner.env.HOME }}/.local/bin" >> $GITHUB_PATH

    - name: Run Ansible Playbook
      run: |
        ansible-playbook playbook.yml

    - name: Run Packer
      run: |
        packer build packer-template.json